Add Route53 support to install, add Brewfile for macOS dependencies
MrSimonEmms/gitpod-k3s-guide pull request #22
Opened 2022-09-28 21:12 UTC by sethvoltz

2022-09-28 21:14 UTC, jontg approved these changes

2022-09-29 07:12 UTC, MrSimonEmms requested changes
Hi @sethvoltz, thanks for your contribution. Much appreciated.

I've left a couple of comments, but there's also a couple of nits I'd like addressing please:
 - can you [rebase](https://www.simonemms.com/blog/2020/11/16/an-introduction-to-git-rebase) to get rid of the merge commit please?
 - normally, I'd prefer two changes (Route53 and Brewfile) to be done as two PRs. Happy for them to be in a single PR, but please do them as two separate commits?

2022-09-29 07:12 UTC, mrsimonemms commented on assets/route53.yaml
> +            region: us-west-1
It feels like the region should be configurable. Remember to add the variable to `.env.example`

```suggestion
            region: ${ROUTE53_REGION}
```

2022-09-30 19:35 UTC, sethvoltz commented on assets/route53.yaml
> +            region: us-west-1
Will do.

2022-09-30 19:39 UTC, closed without merging